"""Stub definitions for graycode (generated by hand).

This file is read by editors, linters and type checkers only; it is NOT imported
at runtime.  Keep the docstring short – full docs live in the compiled symbol.
"""
from __future__ import annotations
from typing import Optional
import numpy as np

def bit_plane(
        bit: int,
        *,
        width: Optional[int] = ...,
        height: Optional[int] = ...,
) -> np.ndarray: ...
