name: Build & Release wheels

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    name: wheel-${{ matrix.os }}-py${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python: [ '3.10', '3.11', '3.12', '3.13' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up CPython
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build wheel with maturin
        uses: PyO3/maturin-action@v1
        with:
          manylinux: auto
          command: build
          args: --release --out wheelhouse --features parallel

      - name: Upload wheel artefact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}-py${{ matrix.python }}
          path: wheelhouse/*.whl
          if-no-files-found: error

  release:
    name: Draft GitHub release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: collected

      - name: Collect wheels into dist/
        run: |
          mkdir -p dist
          find collected -name '*.whl' -exec cp {} dist/ \;

      - name: Create / update release and upload wheels
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
